Output docs/vhs.gif

Set FontSize 18
Set Width 1200
Set Height 680
Set LoopOffset 70%

# Setup
Hide
Set TypingSpeed 0
Type 'export PATH="$PWD:$PATH" && clear'
Enter
Sleep 0.1s
Show

# Recording...
Sleep 2s
Set TypingSpeed 0.05s
Type 'kubectl stratagem'
Sleep 1s
Enter
Sleep 3s

# Reinforce
# 🡅 🡇 🡆 🡄 🡅
Set TypingSpeed 0.3s
Up
Down
Right
Left
Up

Sleep 3s
Escape
Sleep 3s

# Hellbomb
# 🡇 🡅 🡄 🡇 🡅 🡆 🡇 🡅
Set TypingSpeed 0.2s
Down
Up
Left
Down
Up
Right
Down
Up

Screenshot ./docs/vhs.png
Sleep 3s
Escape
Sleep 5s

# Cleanup
Hide
Type 'q'
