Output docs/vhs.gif

Set FontSize 18
Set Width 1200
Set Height 680
Set LoopOffset 55%

# Setup
Hide
Type 'go build -o kubectl-stratagem && export PATH="$PWD:$PATH" && clear'
Enter
Show

# Recording...
Sleep 2s
Set TypingSpeed 0.05s
Type 'kubectl stratagem'
Sleep 1s
Enter
Sleep 3s

# Reinforce
# 🡅 🡇 🡆 🡄 🡅
Set TypingSpeed 0.3s
Up
Down
Right
Left
Up

Sleep 3s
Escape
Sleep 3s

# Hellbomb
# 🡇 🡅 🡄 🡇 🡅 🡆 🡇 🡅
Set TypingSpeed 0.2s
Down
Up
Left
Down
Up
Right
Down
Up

Sleep 3s
Escape
Sleep 5s

# Cleanup
Hide
Type 'q'
Sleep 0.5s
Type 'rm kubectl-stratagem'
Enter
